name: Build Android APK
on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Buildozer Action
      uses: ArtemSBulgakov/buildozer-action@v1
      with:
        workdir: .
        buildozer_version: master
